# Generated by Django 4.0 on 2021-12-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assortment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=100, verbose_name='Товар')),
                ('description_product', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('price_product', models.FloatField(blank=True, null=True, verbose_name='Цена товара')),
                ('photo_product', models.ImageField(blank=True, null=True, upload_to='img_flowers/Category/%Y/%m/%d', verbose_name='Фото товара')),
                ('create_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-create_at'],
            },
        ),
    ]
